#~~~~~~~~~~~~
# Function to strip words and replace with numbers
#~~~~~~~~~~~
change_it <- function(data){
  data <- gsub("^TSRA", 2L, data)
  data <- gsub("^FZFG", 2L, data)
  data <- gsub("^VCTS", 1L, data)
  data <- gsub("^FZRA", 2L, data)
  data <- gsub("^BLSN", 2L, data) 
  data <- gsub("^MIFG", 1L, data) 
  data <- gsub("^BCFG", 1L, data) 
  data <- gsub("^PY", 1L, data)
  data <- gsub("^SQ", 2L, data)
  data <- gsub("^DR", 0L, data)
  data <- gsub("^SH", 1L, data)
  data <- gsub("^PR", 1L, data)
  data <- gsub("^BC", 1L, data)
  data <- gsub("^BL", 1L, data)
  data <- gsub("^VC", 1L, data)
  data <- gsub("^+\\FC", 3L, data)
  data <- gsub("^FC", 2L, data)
  data <- gsub("^TS", 1L, data)
  data <- gsub("^GR", 2L, data)
  data <- gsub("^RA", 1L, data)
  data <- gsub("^DZ", 1L, data)
  data <- gsub("^MI", 0L, data)
  data <- gsub("^SN", 1L, data)
  data <- gsub("^FZ", 2L, data)
  data <- gsub("^SG", 0L, data)
  data <- gsub("^GS", 2L, data)
  data <- gsub("^PL", 2L, data)
  data <- gsub("^IC", 1L, data)
  data <- gsub("^FG\\+", 2L, data)
  data <- gsub("^FG", 1L, data)
  data <- gsub("^BR", 0L, data)
  data <- gsub("^UP", 0L, data)
  data <- gsub("^HZ", 1L, data)
  data <- gsub("^FU", 1L, data)
  data <- gsub("^VA", 1L, data)
  data <- gsub("^SA", 1L, data)
  data <- gsub("^SS", 1L, data)
  data <- gsub("^DU", 2L, data)
  data <- gsub("^DS", 3L, data)
  data <- gsub("^PO", 1L, data)
  data <- gsub("\\+", "", data)
  data <- gsub("\\ ", "", data)
  data <- as.numeric(data)
}



